---
ansible_user: root
ansible_ssh_private_key_file: ~/.ssh/mrazotto/vscale

logging_file_name: log/bl.log

kafka_ext_bootstrap: ift-bl-bootstrap
kafka_ext_security_protocol: ift-bl-security-protocol
