- name: Deploy CERBERS [aserver] - Hi message!
  debug:
    msg: "Aserver is changing!.."

- name: Deploy CERBERS [aserver] - unarchive blserver
  unarchive:
    src: "{{distr_dest}}/nydus.zip"
    dest: "{{ops_dest}}"
    include:
      - aserver/*
    remote_src: yes

