- name: Deploy CERBERS [blserver] - Hi message!
  debug:
    msg: "BLserver is changing!.."

- name: Deploy CERBERS [blserver] - unarchive blserver
  unarchive:
    src: "{{distr_dest}}/nydus.zip"
    dest: "{{ops_dest}}"
    include:
      - arestserver/*
      - autserver/*
      - blserver/*
      - restserver/*
      - cerbers_templates/*
    remote_src: yes

### blserver config --->

- name: Deploy CERBERS [blserver] - Fetch Templates
  fetch:
    src: "{{ops_dest}}/cerbers_templates/blserver/config/application.properties.j2"
    dest: "./roles/deploy-cerbers/templates/blserver_application.properties.j2"
    flat: yes

- name: Deploy CERBERS [blserver] - application.properties templating...
  template:
    src: "blserver_application.properties.j2"
    dest: "{{ops_dest}}/blserver/config/application.properties"

- name: Deploy CERBERS [blserver] - Delete Templates on slave
  file:
    path: "{{ops_dest}}/cerbers_templates"
    state: absent

### restserver arestserver autserver configs --->

