- name: Deploy CERBERS [blserver] - Hi message!
  debug:
    msg: "BLserver is changing!.."

- name: Deploy CERBERS [blserver] - unarchive blserver
  unarchive:
    src: "{{distr_dest}}/nydus.zip"
    dest: "{{ops_dest}}"
    include:
      - blserver/*
      - cerbers_templates/*
    remote_src: yes

- name: Deploy CERBERS [blserver] - Fetch Templates
  fetch:
    src: "{{ops_dest}}/cerbers_templates/blserver/application.properties.j2"
    dest: "roles/deploy-cerbers/templates/blserver/application.properties.j2"

- name: Deploy CERBERS [blserver] - configs templating...
  template:
    src: "roles/deploy-cerbers/templates/blserver/application.properties.j2"
    dest: "{{ops_dest}}/blserver/config/application.properties"

- name: Deploy CERBERS [blserver] - Delete Templates on slave
  file:
    path: "{{ops_dest}}/cerbers_templates"
    state: absent
