- name: Deploy CERBERS - remove old /distr for PACK
  file:
    path: "{{distr_dest}}"
    state: absent

- name: Deploy CERBERS - create new /distr for PACK
  file:
    path: "{{distr_dest}}"
    state: directory

- name: Deploy CERBERS - remove old /ops for PACK
  file:
    path: "{{ops_dest}}"
    state: absent

- name: Deploy CERBERS - create new /ops for PACK
  file:
    path: "{{ops_dest}}"
    state: directory

- name: Deploy CERBERS - zip clone
  git:
    repo: https://github.com/mrazotto/nydus.git
    version: develop
    dest: "{{distr_dest}}"

- name: Deploy CERBERS - unarchive --> blserver <--
  include_role:
    name: deploy-cerbers
    tasks_from: blserver
  when: inventory_hostname.find("blserver") != -1

- name: Deploy CERBERS - unarchive --> aserver <--
  include_role:
    name: deploy-cerbers
    tasks_from: aserver
  when: inventory_hostname.find("aserver") != -1

- name: Deploy CERBERS - Re-create DB
  include_role:
    name: deploy-cerbers
    tasks_from: re-create-db
  when: inventory_hostname.find("_st_")  != -1 or
        inventory_hostname.find("_ift_") != -1 or
        inventory_hostname.find("_psi_") != -1
